# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79221e4a278e2cace1b9772ec62ffec9500781dd7148321f67fe8f00c72af03f47853cf709c7d61d76e24114227aeaa1ae011e459c49e12f7632753718f0016b

test:
  secret_key_base: 47731cf5328ac539404961c0a3cc888407fd9de735a9e1c81e4e551cb7bef3c3769ccf027d0056951c95df70d6d493baa3d953ca04f8987b8cf90fcd14f66afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
